version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"

  ob-item-service:
    build: .
    container_name: ob-item-service
    ports:
      - "8082:8081"
    depends_on:
      - mongodb